# Generated by Django 4.1 on 2022-08-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoardsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoardsApp.list')),
            ],
        ),
    ]
