# Generated by Django 4.1 on 2022-08-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardsApp', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Description',
        ),
    ]
