# Generated by Django 4.1 on 2022-08-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardsApp', '0005_remove_list_description_card_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Description',
        ),
    ]
