# Generated by Django 4.1 on 2022-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardsApp', '0007_card_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
